---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-credentials
  namespace: app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    api-secret-key: AgCU2sxamD2B82HVPGP0a5RUkn91LHEzo2g3Blj+8FFbaXNbT143Q6d4wCpmvQKf40aMMCTQCxe3FXMXVb9ve0m7M2Do54SYm43GpSJq+BBeVfS4sPqMMw3UuvjnBaPZUwSd7rGoQ12VaLbJHpaPygYVitTLRxQOsOb0SLmQ045Q4KsJx9wn6lbM0gsMlk2HmmFEKpC2mVpVY+Sy8umh6ac6Xw/PagQCIUaapP5nyD3EtIoM/tspbu/UH/zHC6dxp4mAfU5Dfb7ao5JQDPKJC/m/vnFhG8nLD7XoXl5cKg3HoQsNZQpWMIrHh73fUwy+tIsyz1dgTExkVXoz/7Kxq9/ONxfS0KR4P9JYTT2DhxIsk+NqOZk2VUbOauJWYTyF8bFRYFeMXfMX/rohgxWwKLB/xFfmpQEyAqCPG3qrh8h4i3HeRFjk0Zf1N8RmcpGOI85vGC2NNOOdWfWGGJ+FcIg9q21VcgePWhyOt1lDQBS7iuWc/EA32gP8+WGrL6svZ5V4tNLZxyvZzHndCc9xMn6Avn2diuDc3bW0xa1iH0bksYFrreMirzD6EwjBt5tO4zdySXzu2lK+8IVmMMpdCcE4yQSYKyhRM3jgtJq8q2oYOIkDShii/JJG6h5hqe21Gl8t7nn6ZCnN/vjNkVJ1zeBLjP16LAWe/SwAW1uepKBww9tkSYZ6wYA9QNtrE2PQCc7oqACRjrzTg3FAuiOBe5GU6fykIAC8hALWkOmibg==
  template:
    metadata:
      name: app-credentials
      namespace: app
    type: Opaqu
#temp