apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: major-project
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
