apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: app
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: major-project
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: major-project
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001

      containers:
        - name: redis
          image: redis:alpine
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 50Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 100Mi
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3

      volumes:
        - name: tmp
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
