apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# images block populated on promotion from dev
# images:
#   - name: major-project-api-service
#     newName: localhost:5000/major-project-api-service
#     newTag: <sha>
#   - name: major-project-worker-service
#     newName: localhost:5000/major-project-worker-service
#     newTag: <sha>
#   - name: major-project-chaos-service
#     newName: localhost:5000/major-project-chaos-service
#     newTag: <sha>
