apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chaos-service
  namespace: app
  labels:
    app: chaos-service
    app.kubernetes.io/name: chaos-service
    app.kubernetes.io/part-of: major-project
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chaos-service
