apiVersion: v1
kind: Service
metadata:
  name: chaos-service
  namespace: app
  labels:
    app: chaos-service
    app.kubernetes.io/name: chaos-service
    app.kubernetes.io/part-of: major-project
spec:
  selector:
    app: chaos-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
