apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: gitops
  labels:
    app.kubernetes.io/part-of: major-project
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vatsalm720/major-project-gitops.git
    targetRevision: main
    path: apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
