apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook-listener-app
  namespace: gitops
  labels:
    app.kubernetes.io/part-of: major-project
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/vatsalm720/major-project-gitops.git
    targetRevision: main
    path: monitoring/webhook-listener
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
